site_name: raina-schematic
site_url: https://raina-rise.github.io/schematic-release/
nav:
  - Overview: overview.md
  - Quick Start: quick-start.md
  - API Reference: api.md

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - search.suggest
    - search.highlight

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed